name: OEM GSI Builder 

on: 
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Load Configuration
        uses: falti/dotenv-action@v0.2.5
        id: config
        with:
          path: config.env
      - name: Download Tools
        run: |
          git clone --recurse-submodules ${{ steps.config.outputs.tool_repo }}
      - name: Set Up Requirements
        run: |
          bash ErfanGSIs/setup.sh
      - name: Pre-Build
        run: |
          sed -i '$d' ErfanGSIs/url2GSI.sh
      - name: Build AB and AOnly
        if: ${{ steps.config.outputs.output_type == 'all' }}
        run: |
          sudo ./ErfanGSIs/url2GSI.sh ${{ steps.config.outputs.url }} ${{ steps.config.outputs.firmware_type }} ${{ steps.config.outputs.extra_args }}
      - name: Build AB
        if: ${{ steps.config.outputs.output_type == 'ab' }}
        run: |
          sudo ./ErfanGSIs/url2GSI.sh ${{ steps.config.outputs.url }} ${{ steps.config.outputs.firmware_type }} --ab ${{ steps.config.outputs.extra_args }}
      - name: Build AOnly
        if: ${{ steps.config.outputs.output_type == 'a' }}
        run: |
          sudo ./ErfanGSIs/url2GSI.sh ${{ steps.config.outputs.url }} ${{ steps.config.outputs.firmware_type }} --aonly ${{ steps.config.outputs.extra_args }}
      - name: Pre-Upload
        run: |
          mkdir build/
          sudo mv ErfanGSIs/output/*.img build/
          gzip -r build/
          sudo mv ErfanGSIs/output/*.txt build/
      - name: Upload
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: sftp://frs.sourceforge.net:22/${{ steps.config.outputs.sourceforge_dir }}
          ftp-username: ${{ secrets.USERNAME }}
          ftp-password: ${{ secrets.PASSWORD }}
          local-dir: 'build/'
          git-ftp-args: --insecure